### ISSUE TITLE
is this fabric or forge

### ISSUE THREAD

**Issue by Lamar1526** [nodusclient/girlboss#1]

**Comment by AstroSquared** [comment]
yes

**Comment by mdo992** [comment]
This is not a fabric mod, there is no reference to "fabric" in the project.

**Comment by AstroSquared** [comment]
> This is not a fabric mod, there is no reference to "fabric" in the project.

Tell me you didn't look without telling me you didn't look
![image](https://user-images.githubusercontent.com/67833955/183321790-7ea9e088-ff85-4e55-b8a8-ce723fb8d7c3.png)
https://github.com/nodusclient/girlboss/blob/562e4478e42dcce49429d6be7e5b77f2a76dd694/build.gradle#L20

**Comment by mdo992** [comment]
> > This is not a fabric mod, there is no reference to "fabric" in the project.
> 
> Tell me you didn't look without telling me you didn't look ![image](https://user-images.githubusercontent.com/67833955/183321790-7ea9e088-ff85-4e55-b8a8-ce723fb8d7c3.png)
> 
> https://github.com/nodusclient/girlboss/blob/562e4478e42dcce49429d6be7e5b77f2a76dd694/build.gradle#L20

Is sarcasm a thing in your culture? It’s fairly obvious that it is a Fabric mod. I’m sorry if you didn’t catch on.

**Comment by Dogocoton** [comment]
Hey calm down

**Comment by ghost** [comment]
its a forge mod!!111

**Comment by 0xAda** [comment]
skill issue
